### ISSUE TITLE
你好，打扰了，请问在epos2，IPM模式下，可以做到同步控制多轴吗？

### ISSUE THREAD

**Issue by zhangstar3** [linghuix/Epos2_CanOpen_Controller#1]
你好，打扰了，请问在epos2，IPM模式下，可以做到同步控制多轴吗？
不知道可以交流一下吗？

**Comment by linghuix** [comment]
你好，很抱歉，我目前还没有用单片机实现过 IPM 模式。只是之前用过 labview 实现四个电机的控制，当时指令发送间隔短一些同步效果就会比较差，但是据我的理解 CANOpen 协议是可以保证数据传输到多个 EPOS2 是同步的。之后就转单片机控制了，位置模式，控制周期短点也能满足要求。

**Comment by linghuix** [comment]
主要看你的应用要求了，如果控制指令间隔要求不高的话（我当时能运行的时间间隔是 100ms 以上 / 四个电机同步），用 Labview 是可以的。

**Comment by zhangstar3** [comment]
> 你好，很抱歉，我目前还没有用单片机实现过 IPM 模式。只是之前用过 labview 实现四个电机的控制，当时指令发送间隔短一些同步效果就会比较差，但是据我的理解 CANOpen 协议是可以保证数据传输到多个 EPOS2 是同步的。之后就转单片机控制了，位置模式，控制周期短点也能满足要求。

你好，上面提到四个电机时，指令发送间隔短一些同步效果就会比较差？？
这句话有点不太明白，感觉如果是毫秒级别差距的话，是可以容忍的；
另外位置模式PM，我试了下，给定位置后，它到达目标点后会停止下来，这样会不会看起来电机一顿一顿的，就是在不停的启停启停？
可以给定一系列递增目标点后，让其连续运转吗？

**Comment by linghuix** [comment]
> 你好，上面提到四个电机时，指令发送间隔短一些同步效果就会比较差？？
> 这句话有点不太明白，感觉如果是毫秒级别差距的话，是可以容忍的；

labview 实现四个电机的控制时，同步效果是可以的，只是控制电机的指令发送间隔不能太短，否则根本无法工作。不清楚labview 内部的实现机理，看你要求了

**Comment by linghuix** [comment]
> 另外位置模式PM，我试了下，给定位置后，它到达目标点后会停止下来，这样会不会看起来电机一顿一顿的，就是在不停的启停启停？
> 可以给定一系列递增目标点后，让其连续运转吗？

我也遇到了这个问题，当时用labview一直搞不定，后来觉得是控制指令给的周期太长了，所以会出现在一个控制周期还没结束时就到达目标点停止下来的情况。所以尝试用单片机去控制，现在5个电机可以用位置模式实现20ms的控制周期(之前labview是几百ms)。连续给目标值，运行还是挺稳定的。

**Comment by zhangstar3** [comment]
@linghuix 好的，非常感谢了；
这样的话，那我试试PM模式；
不知道你试过它的PPM模式了吗，它这个也是给定QC，看起来也稍微复杂了一点点。
